# -*- coding: utf-8 -*-
"""PandasKrishNaik.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7Qj9PIRpzerX2l-8wZIhMHeduTqHAi6
"""

import pandas as pd
import numpy as np

given = np.arange(0,20).reshape(5,4)

df = pd.DataFrame(data=given, index=['Row1', "Row2", "Row3", 'Row4', 'Row5'], columns=['column1', 'column2', 'column3', 'column4'])

print(df.head())